# Generated by Django 2.2 on 2019-05-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvranker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='age',
            field=models.IntegerField(),
        ),
    ]
